language: python

# Setting sudo to false opts in to Travis-CI container-based builds.
sudo: false

# The apt packages below are needed for sphinx builds.
addons:
    apt:
        packages:
            - graphviz
            - texlive-latex-extra
            - dvipng

python:
    - 2.7
    - 3.5

env:
    global:
        - NUMPY_VERSION=stable
        - ASTROPY_VERSION=stable
        - CONDA_DEPENDENCIES='matplotlib pyparsing Cython'
        - SETUP_CMD='test'
        - SETUP_XVFB=True
        - CONDA_CHANNELS='astropy-ci-extras'

    matrix:
        - SETUP_CMD='egg_info'
        - SETUP_CMD='test'

matrix:
    include:

        # The main test, where we measure coverage
        - python: 3.6
          env: SETUP_CMD='test --coverage'

        # Check for sphinx doc build warnings - we do this first because it
        # may run for a long time
        - python: 2.7
          env: SETUP_CMD='build_docs' PIP_DEPENDENCIES='sphinx_rtd_theme'
        - python: 3.5
          env: SETUP_CMD='build_docs -w' PIP_DEPENDENCIES='sphinx_rtd_theme'

        # Try Astropy development and LTS version
        - python: 3.6
          env: ASTROPY_VERSION=development
        - python: 2.7
          env: ASTROPY_VERSION=lts
        - python: 3.5
          env: ASTROPY_VERSION=lts

        # Try older numpy versions
        - python: 3.4
          env: NUMPY_VERSION=1.11
        - python: 2.7
          env: NUMPY_VERSION=1.10
        - python: 2.7
          env: NUMPY_VERSION=1.9
        - python: 2.7
          env: NUMPY_VERSION=1.8
        - python: 3.6
          env: NUMPY_VERSION=1.13

        # Try numpy pre-release
        - python: 3.5
          env: NUMPY_VERSION=prerelease

install:
    - git clone git://github.com/astropy/ci-helpers.git
    - source ci-helpers/travis/setup_conda.sh

script:
   - python setup.py $SETUP_CMD

after_success:
    - if [[ $SETUP_CMD == 'test --coverage' ]]; then
          coveralls --rcfile='pyregion/tests/coveragerc';
      fi
